# Generated by Django 2.0.1 on 2018-03-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20180317_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='sportsfield_included',
            new_name='included_sports_field',
        ),
    ]
