# Generated by Django 2.0.1 on 2018-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20180317_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='included_sports_field',
            field=models.ManyToManyField(blank=True, to='WebApp.SportsField'),
        ),
    ]
