# Generated by Django 2.0.1 on 2018-04-01 17:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('WebApp', '0005_auto_20180317_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('self_introduction', models.TextField(blank=True, help_text='You could introduce yourself here.')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('Reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reciever', to=settings.AUTH_USER_MODEL)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='sportsfield',
            old_name='remaark',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='holiday_booking_fare_adult',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='holiday_booking_fare_children',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='holiday_booking_fare_disabled',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='holiday_booking_fare_senior',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='holiday_booking_fare_student',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='working_day_booking_fare_adult',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='working_day_booking_fare_children',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='working_day_booking_fare_disabled',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='working_day_booking_fare_senior',
        ),
        migrations.RemoveField(
            model_name='sportsfield',
            name='working_day_booking_fare_student',
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facility',
            name='opening_hour',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='district',
            field=models.CharField(default='Sha Tin', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='need_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='opening_hour',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='payment_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='can_be_booked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Facility'),
        ),
    ]
