# Generated by Django 2.0.1 on 2018-04-02 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20180402_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rate', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, help_text='Required. Input your date of birth.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Male', help_text='Required. Choose according to your gender.', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', help_text='Please select the sports that you are interested.', max_length=166),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='fucker', help_text='Please enter your nickname.', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='propic_url',
            field=models.CharField(blank=True, help_text='You could upload your personal profile picture.', max_length=300),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_indoor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='rate_denominator',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='rate_numerator',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='sports_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', max_length=166),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='rate_denominator',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='rate_numerator',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='sports_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', max_length=166),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='blocked_user',
            field=models.ManyToManyField(related_name='Blocked_User', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blacklist_Owner', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='included_sports_field',
            field=models.ManyToManyField(to='WebApp.SportsField'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='opening_hour',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ManyToManyField(related_name='Friend', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendList_Owner', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reciever', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(help_text='Please type your message here.'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='comment',
            field=models.TextField(help_text='Please type your opinion here. Your opinion would be handled within five working days.'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='email',
            field=models.EmailField(blank=True, help_text='Please type your email here if you want a reply.', max_length=254),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='target',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.Facility'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Founder', to='WebApp.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='can_be_booked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='is_free',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='need_membership',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='opening_hour',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='payment_detail',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='commentonfacilities',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to='WebApp.CustomUser'),
        ),
        migrations.AddField(
            model_name='commentonfacilities',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facility', to='WebApp.Facility'),
        ),
    ]
