# Generated by Django 2.0.1 on 2018-04-02 14:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20180402_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='propic_url',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='included_sports_field',
        ),
        migrations.AddField(
            model_name='customuser',
            name='propic',
            field=models.ImageField(blank=True, help_text='You could upload your personal profile picture.', upload_to='', verbose_name='Profile picture'),
        ),
        migrations.AddField(
            model_name='facility',
            name='included_sportsfield',
            field=models.ManyToManyField(to='WebApp.SportsField', verbose_name='Included sportsfield'),
        ),
        migrations.AddField(
            model_name='facility',
            name='rate',
            field=models.CharField(default='N/A', max_length=4, verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='sportsfield',
            name='rate',
            field=models.CharField(default='N/A', max_length=4, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(help_text='Required. Input your date of birth.', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(help_text='Required. Choose according to your gender.', max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', help_text='Please select the sports that you are interested.', max_length=166, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(help_text='Please enter your nickname.', max_length=150, unique=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='self_introduction',
            field=models.TextField(blank=True, help_text='You could introduce yourself here.', verbose_name='Self introduction'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='district',
            field=models.CharField(max_length=25, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_indoor',
            field=models.BooleanField(verbose_name='Is indoor'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.TextField(default='', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='opening_hour',
            field=models.TextField(verbose_name='Opening hour'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='remark',
            field=models.TextField(verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sports_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', max_length=166, verbose_name='Sports type'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='can_be_booked',
            field=models.BooleanField(verbose_name='Can be booked'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='district',
            field=models.CharField(max_length=25, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='is_free',
            field=models.BooleanField(verbose_name='Is free'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='is_indoor',
            field=models.BooleanField(verbose_name='Is indoor'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='location',
            field=models.TextField(default='', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='need_membership',
            field=models.BooleanField(verbose_name='Membership'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='opening_hour',
            field=models.TextField(verbose_name='Opening hour'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='payment_detail',
            field=models.TextField(verbose_name='Charge'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='remark',
            field=models.TextField(verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='sports_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', max_length=166, verbose_name='Sports type'),
        ),
    ]
