# Generated by Django 2.0.1 on 2018-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20180402_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='facility',
            name='rate_denominator',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='facility',
            name='rate_numerator',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='rate_denominator',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='rate_numerator',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
    ]
