# Generated by Django 2.0.1 on 2018-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_auto_20180403_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], help_text='Required. Choose according to your gender.', max_length=1, verbose_name='Gender'),
        ),
    ]
