# Generated by Django 2.0.1 on 2018-04-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_auto_20180403_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Required. Choose according to your gender.', max_length=1, verbose_name='Gender'),
        ),
    ]
