# Generated by Django 2.0.1 on 2018-04-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_auto_20180403_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
    ]
