# Generated by Django 2.0.1 on 2018-04-03 06:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_auto_20180403_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('running', 'Running'), ('skipping', 'Skipping'), ('softball', 'Softball'), ('squash', 'Squash'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', help_text='Optional. Please select the sports that you are interested.', max_length=166, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(help_text='Required. Please enter your nickname.', max_length=150, unique=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='propic',
            field=models.ImageField(blank=True, help_text='Optional. You could upload your personal profile picture.', upload_to='', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='self_introduction',
            field=models.TextField(blank=True, help_text='Optional. You could introduce yourself here.', verbose_name='Self introduction'),
        ),
    ]
