# Generated by Django 2.0.3 on 2018-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_auto_20180403_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsfield',
            name='address',
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
            preserve_default=False,
        ),
    ]
