# Generated by Django 2.0.1 on 2018-04-03 14:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_auto_20180403_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('climbing', 'Climbing'), ('cycling', 'Cyling'), ('dancing', 'Dancing'), ('dodgeball', 'Dodgeball'), ('football', 'Football'), ('golf', 'Golf'), ('gymnasium', 'Gymnasium'), ('hiking', 'Hiking'), ('pool', 'Pool'), ('running', 'Running'), ('skipping', 'Skipping'), ('snooker', 'Snooker'), ('softball', 'Softball'), ('squash', 'Squash'), ('swimming', 'Swimming'), ('table_tennis', 'Table Tennis'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('woodball', 'Woodball'), ('others', 'Others')], default='', help_text='Optional. Please select the sports that you are interested.', max_length=197, verbose_name='Interest'),
        ),
    ]
