# Generated by Django 2.0.1 on 2018-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_auto_20180403_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='district',
            field=models.CharField(choices=[('Central and Western', 'Central and Western'), ('Wanchai', 'Wanchai'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Kowloon City', 'Kowloon City'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Kwun Tong', 'Kwun Tong'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Sham Shui Po', 'Sham Shui Po'), ('Tsuen Wan', 'Tsuen Wan'), ('Kwai Tsing', 'Kwai Tsing'), ('Sai Kung', 'Sai Kung'), ('Shatin', 'Shatin'), ('Tai Po', 'Tai Po'), ('Northern', 'Northern'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Island', 'Island')], max_length=3, verbose_name='District'),
        ),
    ]
