# Generated by Django 2.0.1 on 2018-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_auto_20180403_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='district',
            field=models.CharField(choices=[('CAW', 'Central and Western District'), ('WC', 'Wanchai District'), ('E', 'Eastern District'), ('S', 'Southern District'), ('KNC', 'Kowloon City District'), ('WTS', 'Wong Tai Sin District'), ('KT', 'Kwun Tong District'), ('YTW', 'Yau Tsim Mong District'), ('SSP', 'Sham Shui Po District'), ('TW', 'Tsuen Wan District'), ('KT', 'Kwai Tsing District'), ('SK', 'Sai Kung District'), ('ST', 'Shatin District'), ('TP', 'Tai Po District'), ('N', 'Northern District'), ('TM', 'Tuen Mun District'), ('YL', 'Yuen Long District'), ('I', 'Island District')], max_length=3, verbose_name='District'),
        ),
    ]
