# Generated by Django 2.0.1 on 2018-04-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0026_auto_20180406_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='longitude',
            new_name='lng',
        ),
    ]
