# Generated by Django 2.0.1 on 2018-04-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_auto_20180406_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='lng',
            new_name='longitude',
        ),
    ]
