# Generated by Django 2.0.1 on 2018-04-07 08:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0028_auto_20180406_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Badminton', 'Badminton'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Climbing', 'Climbing'), ('Cycling', 'Cycling'), ('Dancing', 'Dancing'), ('Dodgeball', 'Dodgeball'), ('Football', 'Football'), ('Golf', 'Golf'), ('Gymnasium', 'Gymnasium'), ('Hiking', 'Hiking'), ('Pool', 'Pool'), ('Running', 'Running'), ('Skipping', 'Skipping'), ('Snooker', 'Snooker'), ('Softball', 'Softball'), ('Squash', 'Squash'), ('Swimming', 'Swimming'), ('Table Tennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Woodball', 'Woodball'), ('Others', 'Others')], default='', help_text='Optional. Please select the sports that you are interested.', max_length=197, verbose_name='Interest'),
        ),
    ]
