# Generated by Django 2.0.1 on 2018-04-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_auto_20180407_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ('blocked_user__nickname',)},
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='owner',
            new_name='blocklist_owner',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='owner',
            new_name='friendlist_owner',
        ),
    ]
