# Generated by Django 2.0.1 on 2018-04-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0030_auto_20180407_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentonsportsfield',
            old_name='sportsfield',
            new_name='target_sportsfield',
        ),
        migrations.RemoveField(
            model_name='commentonfacility',
            name='facility',
        ),
        migrations.AddField(
            model_name='commentonfacility',
            name='target_facility',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Facility', to='WebApp.Facility'),
            preserve_default=False,
        ),
    ]
