# Generated by Django 2.0.1 on 2018-04-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0032_remove_facility_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentonfacility',
            name='target_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentTargetedFacility', to='WebApp.Facility'),
        ),
        migrations.AlterField(
            model_name='commentonsportsfield',
            name='target_sportsfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentTargetedSportsField', to='WebApp.SportsField'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='target_facility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='OpinionTargetedFacility', to='WebApp.Facility'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='target_sportsfield',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='OpinionTargetedSportsField', to='WebApp.SportsField'),
        ),
    ]
