# Generated by Django 2.0.3 on 2018-05-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0033_auto_20180417_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='propic',
            field=models.ImageField(blank=True, default='default_propic.png', help_text='Optional. You could upload your personal profile picture.', upload_to='propic_img/', verbose_name='Propic'),
        ),
    ]
