# Generated by Django 2.0.3 on 2018-05-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0034_auto_20180502_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='propic',
            field=models.ImageField(blank=True, default='default_propic.png', help_text='Optional. You could upload your personal profile picture.', upload_to='', verbose_name='Propic'),
        ),
    ]
