# Generated by Django 2.0.3 on 2018-05-03 05:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0036_auto_20180502_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='appointment time')),
                ('sports_type', models.CharField(choices=[('Badminton', 'Badminton'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Climbing', 'Climbing'), ('Cycling', 'Cycling'), ('Dancing', 'Dancing'), ('Dodgeball', 'Dodgeball'), ('Football', 'Football'), ('Golf', 'Golf'), ('Gymnasium', 'Gymnasium'), ('Hiking', 'Hiking'), ('Pool', 'Pool'), ('Running', 'Running'), ('Skipping', 'Skipping'), ('Snooker', 'Snooker'), ('Softball', 'Softball'), ('Squash', 'Squash'), ('Swimming', 'Swimming'), ('Table Tennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Woodball', 'Woodball'), ('Others', 'Others')], default='', max_length=25, verbose_name='Sports')),
                ('location', models.CharField(max_length=100)),
                ('max_num', models.PositiveIntegerField(default=1)),
                ('joined', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('O', 'open'), ('F', 'full'), ('E', 'ended')], default='O', max_length=1)),
                ('remark', models.TextField(blank=True)),
                ('participants', models.CharField(default='[]', max_length=100000)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Starter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
