# Generated by Django 2.0.3 on 2018-05-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='blocked_user',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='blocklist_owner',
        ),
        migrations.RemoveField(
            model_name='commentonfacility',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='commentonfacility',
            name='target_facility',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='friendlist_owner',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='target_facility',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='target_sportsfield',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='founder',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Starter', to='WebApp.CustomUser'),
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='CommentOnFacility',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
